/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* cells_not_processed =  1  *)
(* src = "ha.v:1" *)
module half_adder(a, b, sum, co);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "ha.v:2" *)
  input a;
  (* src = "ha.v:2" *)
  input b;
  (* src = "ha.v:3" *)
  output co;
  (* src = "ha.v:3" *)
  output sum;
  NOT _3_ (
    .A(a),
    .Y(_0_)
  );
  NOT _4_ (
    .A(b),
    .Y(_1_)
  );
  NOR _5_ (
    .A(_0_),
    .B(_1_),
    .Y(co)
  );
  NOR _6_ (
    .A(a),
    .B(b),
    .Y(_2_)
  );
  NOR _7_ (
    .A(co),
    .B(_2_),
    .Y(sum)
  );
endmodule
