/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

module half_adder(a, b, sum, co);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input a;
  input b;
  output co;
  output sum;
  sky130_fd_sc_hd__and2_0 _4_ (
    .A(_1_),
    .B(_0_),
    .X(_2_)
  );
  sky130_fd_sc_hd__xor2_1 _5_ (
    .A(_1_),
    .B(_0_),
    .X(_3_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign sum = _3_;
  assign co = _2_;
endmodule
